title: "Paper Picnic ðŸ§º"
email: "hello@paper-picnic.com"
author: "Moritz Marbach"
description: "A weekly basket with the latest published research in political science."
baseurl: ""
url: "https://www.paper-picnic.com"
github_username: "sumtxt"
exclude: 
  - "Gemfile"
  - "Gemfile.lock"
  - credentials.R