name: Update stats

on: 
   workflow_dispatch:

jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::jsonlite

      - name: Check out repository
        uses: actions/checkout@v4
        with:
          path: main_folder
          ref: main

      - name: Get data and produce JSON
        working-directory: ./main_folder
        run: |
          Rscript stats.R

      - name: Commit results main branch 
        working-directory: ./main_folder
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add . && git commit -m "Data updated"
          git push origin

      - name: Check out repository
        uses: actions/checkout@v4
        with:
          path: gh_pages_folder
          ref: gh-pages

      - name: Commit to gh-pages branch 
        working-directory: ./gh_pages_folder
        run: |
          cp -f ../main_folder/output/stats.csv ./_data/stats.csv
          cp -f ./_data/stats.csv ./json/stats.csv
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add . && git commit -m "Data updated"
          git push origin
